config/routes.rb
Rails.application.routes.draw do

  root 'houses#map'
  get 'visualisation/scatter'
  # get 'visualisation/bar'
  get 'visualisation/heatmap'
  get 'visualisation/threedim'
  get 'visualisation/tableau'

  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  resources :houses, only: [:create, :index, :show] do
    collection do
      get 'export'
      get 'filter'
      get 'return_houses'
      get 'return_nums_prices'
    end
    member do
      get 'nearby'
    end
  end

  resources :spiders, only: [:create, :index] do
    collection do
      get 'return_next'
      get 'export_bus'
      get 'export_bus_house'
    end
  end

  resources :hospitals, only: [:create, :index] do
    collection do
      get 'ajax'
    end
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/spiders_controller.rb
class SpidersController < ApplicationController

  # TODO
  # 增加权限控制，只有管理员才能调用return_next和create
  # END

  @@house_id=0

  def return_next
    # 查询下一个房屋信息
    house=House.next_record(@@house_id)
    @@house_id=house.id

    # 避免重复抓取，跳过已经有相关信息的
    while not house.buses_houses.nil? and not house.buses_houses.blank?
      house=House.next_record(@@house_id)
      @@house_id=house.id
      break if house == House.last
    end

    # TODO
    # 避免重复抓取，现在只能靠bus信息进行判断，希望更全面的信息判断
    # END

    if house == House.last
      redirect_to buses_path, flash: {:success => "抓取完毕"}
    else
      respond_to do |format|
        format.json { render :json => house }
      end
    end
  end

  def index
  end

  def create
    house=House.find_by(id: params[:id])
    house.latitude=params[:lat]
    house.longitude=params[:lng]
    house.save

    insert(house, params, Bus, BusesHouses, 'bus') if params[:nearby_type] == 'bus'
    insert(house, params, Hospital, HospitalsHouses, 'hospital') if params[:nearby_type] == 'hospital'
    insert(house, params, Work, WorksHouses, 'work') if params[:nearby_type] == 'work'
    insert(house, params, School, SchoolsHouses, 'school') if params[:nearby_type] == 'school'
    insert(house, params, Subway, SubwaysHouses, 'subway') if params[:nearby_type] == 'subway'
    insert(house, params, Bus, ShopsHouses, 'shop') if params[:nearby_type] == 'shop'

    render json: params.as_json
  end


  # TODO
  # bus数据的导出，需要自己写前端
  # END
  def export_bus
    respond_to do |format|
      format.csv { send_data Bus.to_csv, filename: "buses-#{Date.today}.csv" }
    end
  end

  def export_bus_house
    respond_to do |format|
      format.csv { send_data BusesHouses.to_csv, filename: "buses_houses-#{Date.today}.csv" }
    end
  end

end

app/views/spiders/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header">抓取附近 </h3>
    <!--TODO Task1-->
    <!--将房屋信息移植到这里显示，去掉当前房屋信息Panel-->
    <!--END-->
  </div>
</div>

<div class="row">
  <div class="col-sm-4">

    <!--TODO Task2-->
    <!--增加进度条，实时显示抓取的进度-->
    <!--END-->

    <div class="panel panel-default">
      <div class="panel-heading">
        当前房屋信息:
      </div>
      <div class="panel-body">
        <table>
          <tr>
            <td style="width: 20%">ID:</td>
            <td id="id"></td>
          </tr>
          <tr>
            <td style="width: 20%">小区:</td>
            <td id="community"></td>
          </tr>
          <tr>
            <td style="width: 20%">地址:</td>
            <td id="street"></td>
          </tr>
        </table>
      </div>
    </div>

    <!--TODO Task3-->
    <!--分抓取的类别实时返回周边数据，现在是所有的数据都在一个panel显示-->
    <!--提示：增加多个panel，每一个panel显示一类数据，比如bus_panel里显示抓取的bus信息-->
    <!--END-->

    <div class="panel panel-default">
      <div class="panel-heading">
        实时返回周边数据

      </div>
      <div class="panel-body">
        <table id="result" class="table table-responsive table-condensed table-hover">
          <thead>
          <tr>
            <th>ID</th>
            <th>地点名</th>
            <th>直线距离</th>
          </tr>
          </thead>
          <tbody style="font-size: small">
          </tbody>
        </table>
      </div>
    </div>

  </div>

  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        百度地图API
        <div class="pull-right">
          <button class="btn btn-success btn-xs" onclick="flag = false;GetDataFromServer();">开始</button>
          <button class="btn btn-danger btn-xs" onclick="flag=true;">暂停</button>
        </div>
      </div>
      <div class="panel-body">
        <div id="l-map" style="height: 500px;width: 100%">
        </div>
      </div>
    </div>
  </div>

</div>

<script type="text/javascript">

    var get_data_url = "<%=return_next_spiders_path%>";
    var post_data_url = "<%=spiders_path%>";
    var timeInterval = 100;
    var flag = false;
    var search_range = 1000;

    // 两个数组的顺序不能错
    var keywords_en = ["bus", "shop", "school", "subway", "work", "hospital"];
    var keywords = ["公交车站", "商场", "学校", "地铁站", "写字楼", "医院"];

    var map = new BMap.Map("l-map");
    // 初始化map坐标为北京,11为比例尺
    map.centerAndZoom(new BMap.Point(116.404, 39.915), 11);
    map.enableScrollWheelZoom(true);
    var myGeo = new BMap.Geocoder();

    //  var circle = new BMap.Circle(new BMap.Point(116.404, 39.915), search_range, {
    //    fillColor: "blue",
    //    strokeWeight: 1,
    //    fillOpacity: 0.1,
    //    strokeOpacity: 0.3
    //  });
    //  map.addOverlay(circle);

    function displayHouseData(data) {
        $('#id').html(data.id);
        $('#community').html(data.community);
        $('#street').html(data.street);
    }

    function DisplayClear() {
        $('#result tbody tr').remove();
    }

    function DisplayNearbyData(nearby_info, locate, distance) {
        // id, title, distance
        $('#result tbody').append("<tr><td>" + nearby_info.length + "</td><td>" + locate.title + "</td><td>" + distance + "</td></tr>");
    }

    function GetDataFromServer() {
        $.ajax({
            type: "GET",
            url: get_data_url,
            dataType: 'json',
            success: function (house_data) {

                // 拿到房屋数据后先显示出来
                displayHouseData(house_data);

                // 然后先用街道去查坐标
                myGeo.getPoint(house_data.street, function (point) {
                    if (point) {
                        // 如果查到坐标，开始检索周围信息
                        SearchStart(point, house_data);
                    } else {
                        // 如果街道没查搭配，再用小区去查坐标
                        myGeo.getPoint(house_data.community, function (repoint) {
                            if (repoint) {
                                // 如果查到坐标，开始检索周围信息
                                SearchStart(repoint, house_data)
                            } else {
                                setTimeout(function () {
                                    console.log("Error: no address of " + " id: " + data.id + " community: " + data.community + " street: " + data.street);
                                    // 如果还没查到坐标，继续查询下一个房屋，延迟timeInterval秒
                                    GetDataFromServer();
                                }, timeInterval);
                            }
                        }, "北京市");
                    }
                }, "北京市");
            },
            error: function () {
                alert('error')
            },
            timeout: function () {
                alert('time out')
            }
        });
    }


    function SearchStart(point, house_data) {
        // 先在地图上标记出来
        map.centerAndZoom(point, 16);
        map.addOverlay(new BMap.Marker(point));

        // 首先查询此房屋的第一个关键词信息（公交车站，idx＝0）
        setTimeout(function () {
            SearchNearby(point, house_data, 0);
        }, timeInterval);

    }

    function SearchNearby(house_loc, house_data, keyword_idx) {
        var nearby_info = [];
        // 清除地图覆盖物
        map.clearOverlays();
        var local = new BMap.LocalSearch(map, {
            renderOptions: {map: map, autoViewport: false},
            pageCapacity: 50,
            onSearchComplete: function (results) {
                DisplayClear();
                if (local.getStatus() == BMAP_STATUS_SUCCESS) {
                    // 百度地图成功返回，将每个周边信息储存到nearby_info里
                    for (var i = 0; i < results.getCurrentNumPois(); i++) {
                        var locate = results.getPoi(i);
                        if (locate != null) {
                            // 查询结果与房屋的距离
                            var distance = parseFloat(map.getDistance(locate.point, house_loc)).toFixed(1);
                            nearby_info.push(locate.title + "/" + locate.point.lng + '/' + locate.point.lat + '/' + distance);
                            DisplayNearbyData(nearby_info, locate, distance)
                        }
                    }
                    // 获得百度地图查询结果后立即发送给服务器
                    return sendData(keywords_en[keyword_idx], nearby_info, house_data, house_loc, keyword_idx)
                } else {
                    GetDataFromServer();
                    console.log("No records with baiduAPI:", local.getStatus());
                    return false;
                }
            }
        });
        local.searchNearby(keywords[keyword_idx], house_loc, search_range);
    }

    function sendData(nearby_type, nearby_info, house_data, house_loc, idx) {
        data = "nearby_type=" + nearby_type + "&nearby_info=" + nearby_info + "&id=" + house_data.id + "&lat=" + house_loc.lat + "&lng=" + house_loc.lng;
        $.ajax({
            type: "POST",
            url: post_data_url,
            data: data,
            dataType: "JSON",
            success: function (data) {
                if (flag) {
                    console.log("warning", 'pause');
                } else {
                    // 当查询到最后一个kewords时，请求服务器获得下一个房屋信息
                    if (idx == keywords.length - 1) {
                        GetDataFromServer();
                    } else {
                        // 查询此房屋的下一个关键词信息
                        setTimeout(function () {
                            SearchNearby(house_loc, house_data, idx + 1);
                        }, timeInterval);
                    }
                    console.log("success", data);
                }
                return true;
            },
            error: function () {
                alert('error in post');
                return false;
            },
            timeout: function () {
                alert('time out in post');
                return false;
            }
        });
    }


</script>