config/routes.rb
Rails.application.routes.draw do

  root 'houses#map'
  get 'visualisation/scatter'
  # get 'visualisation/bar'
  get 'visualisation/heatmap'
  get 'visualisation/threedim'
  get 'visualisation/tableau'

  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  resources :houses, only: [:create, :index, :show] do
    collection do
      get 'export'
      get 'filter'
      get 'return_houses'
      get 'return_nums_prices'
    end
    member do
      get 'nearby'
    end
  end

  resources :spiders, only: [:create, :index] do
    collection do
      get 'return_next'
      get 'export_bus'
      get 'export_bus_house'
    end
  end

  resources :hospitals, only: [:create, :index] do
    collection do
      get 'ajax'
    end
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_content.html.erb
<div id="wrapper">
  <div id="page-wrapper">

    <% flash.each do |message_type, message| %>
        <br>
        <div class="alert alert-<%= message_type %>">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong> <%= message %></strong>
        </div>
    <% end %>

    <%= yield %>

  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">

  <div class="navbar-header">
    <%= link_to "HousePricing", root_path, method: :get, class: 'navbar-brand' %>
  </div>

  <div class="collapse navbar-collapse">
    <ul class="nav navbar-top-links navbar-right">

      <% if current_user.nil? %>
          <li>
            <button type="button" id="login_panel" class="btn btn-link navbar-btn">
              <span class="glyphicon glyphicon-log-in"></span> 登录
            </button>
          </li>

      <% else %>
          <li>
            <%= link_to sessions_logout_path, method: :delete do %>
                退出 <span class="	glyphicon glyphicon-off"></span>
            <% end %>
          </li>
      <% end %>

      <li> <%= link_to "Github源码", 'https://github.com/PENGZhaoqing/HousePricing' %></li>

    </ul>
    <%= render 'layouts/navside' %>
  </div>
</nav>


<%= render "layouts/login_panel" %>

app/views/layouts/_login_panel.html.erb
<!-- Modal -->
<div class="modal fade" id="panel_modal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="padding:35px 30px;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4><span class="glyphicon glyphicon-lock"></span> 登录</h4>
      </div>
      <div class="modal-body" style="padding:40px 30px;">

        <%= form_for(:session, url: sessions_login_path, method: :post, html: {role: 'form'}) do |f| %>

            <div class="form-group">
              <%= f.label :rand_code, "账号密码登陆" %>
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></div>
                <%= f.email_field :email, class: 'form-control', placeholder: "输入邮箱" %>
              </div>
            </div>

            <div class="form-group">
              <div class="input-group">
                <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                <%= f.password_field :password, class: 'form-control', placeholder: "输入密码" %>
              </div>
            </div>

            <%= button_tag(type: "submit", class: "btn btn-success btn-block") do %>
                <span class="glyphicon glyphicon-off"></span>登陆
            <% end %>

        <% end %>

      </div>

      <div class="modal-footer">
        <p>没有账号?
          <%= link_to "那也没有办法,因为还没开放注册,只有管理员能登录喔", root_path %>
        </p>
      </div>

    </div>

  </div>

</div>

<script>
  $(document).ready(function () {
    $("#login_panel").click(function () {
      $("#panel_modal").modal();
    });
  });

</script>

app/views/layouts/_navside.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li class="sidebar-search">

        <%= form_tag houses_path, method: 'get', role: "search" do %>
            <div class="input-group">
              <%= text_field_tag 'query', params[:query], class: "form-control inpu", placeholder: "搜索关键字" %>
              <div class="input-group-btn">
                <button class="btn btn-default btn" type="submit"><i class="glyphicon glyphicon-search"></i>
                </button>
              </div>
            </div>
        <% end %>

        <!-- /input-group -->
      </li>
      <li>
        <%= link_to root_url, method: :get do %>
            <i class="fa fa-dashboard fa-fw"></i> 地图找房
        <% end %>
      </li>

      <li><%= link_to houses_path, method: :get do %>
            <i class="fa fa-table fa-fw"></i> 房源列表
        <% end %>
      </li>

      <li>
        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> 房价分析 <span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
          <li><%= link_to '散点图', visualisation_scatter_path, method: :get %></li>
          <li> <%= link_to '热力图', visualisation_heatmap_path, method: :get %></li>
          <li> <%= link_to '三维展示', visualisation_threedim_path, method: :get %></li>
          <li> <%= link_to 'Tableau', visualisation_tableau_path, method: :get %></li>

        </ul>
      </li>

      <li><%= link_to spiders_path, method: :get do %>
            <i class="fa fa-map fa-fw"></i> 抓取房屋集周边
        <% end %>
      </li>

    </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HouseMapping</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=ZmMCG4QP5FaX064YxPdgQq1sHLYyjKMA"></script>
  <!--<script type="text/javascript" src="http://api.map.baidu.com/library/TextIconOverlay/1.2/src/TextIconOverlay_min.js"></script>-->
  <!--<script type="text/javascript" src="http://api.map.baidu.com/library/MarkerClusterer/1.2/src/MarkerClusterer_min.js"></script>-->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.0/jquery.scrollTo.min.js"></script>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

</head>
<body>

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>

</body>
</html>